---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# dplyrbench

```{r, eval = FALSE}
dplyrbench::setup_libs()
```

```{r}
library(dplyrbench)
library(dplyr)
library(ggplot2)

# non hybrid
no_hybrid <- benchs({
    mean_ <- function(...) mean(...)
    df <- tibble(x = rnorm(1e6), g = rep(1:1e5, 10)) %>% group_by(g)
  }, 
  summarise(df, x = mean_(x))
) %>% mutate(hybrid = FALSE, expression = "mean_()")

# hybrid
hybrid <- benchs(
  df <- tibble(x = rnorm(1e6), g = rep(1:1e5, 10)) %>% group_by(g),
  summarise(df, x = mean(x))
) %>% mutate(hybrid = TRUE,  expression = "mean()")

# partial hybrid
partial_hybrid <- benchs(
  df <- tibble(x = rnorm(1e6), g = rep(1:1e5, 10)) %>% group_by(g),
  summarise(df, x = sum(x) / n())
) %>% mutate(hybrid = c(TRUE, FALSE, FALSE),  expression = "sum() / n()")

data <- bind_rows(hybrid, no_hybrid, partial_hybrid) %>% 
  select(version, unwind, hybrid, expression, min:mem_alloc)

ggplot(data, aes(y = version, x = median, col = hybrid)) + 
  geom_point(size = 3) + 
  facet_grid(factor(expression, levels = c("mean()", "mean_()", "sum() / n()"))~.) +
  scale_x_log10() + 
  ylab("") 
```
